### ISSUE TITLE
Cuda version 

### ISSUE THREAD

**Issue by coolabhishek** [yuzhimanhua/MATCH#6]
I am seeing the following error

RuntimeError: Expected object of scalar type Long but got scalar type Int for sequence element 1 in sequence argument at position #1 'tensors'

Can you please tell me which version you were using for 
cudatoolkit and cudnn

Thanks
abhishek

**Comment by yuzhimanhua** [comment]
Thanks for your interest in our work. The CUDA version is 11.3. The cuDNN version is 7.6.2.

Best,
Yu
